### PR TITLE
bad_block: add BadBlock and various runtime tests

### PR DESCRIPTION
**Pull request by etschneider**
Just a little block to trigger runtime errors for testing, and some associated tests.

### CODE REVIEW

**Comment by bastibl** [comment]
I cherry-picked this on top of some WIP changes for better error/termination handling: https://github.com/bastibl/FutureSDR (in case you're also working on this atm)

**Comment by etschneider** [comment]
Yep, I just pushed to PR #81. Plenty of overlap. I'll step away to avoid more conflicts.

**Comment by etschneider** [comment]
OT: Is it safe to assume you don't like the "nested use" style. I'll stop using it if so.

**Comment by etschneider** [comment]
Yes, closing is fine.

I like the nested format myself. I find it nice to see what is coming from each crate at a glance. I probably wouldn't go through the trouble manually, but I do use it with automatic formatting.

I have no issue with whatever you choose.

**Pull request closed without merging**
