### PR TITLE
runtime:   do not return error on terminate msg

### PR DESCRIPTION
**Pull request by etschneider**
Also added an Err check in the executor loop of SmolScheduler::new() when testing. Probably should remain in some form.

Left commented-out deadlock code in:
tests/runtime::fg_terminate()

refs: #80

### CODE REVIEW

**Comment by etschneider** [comment]
As an extra note, a test log:

```
FutureSDR: DEBUG - in run_flowgraph
FutureSDR: DEBUG - connect stream io
FutureSDR: DEBUG - connect message io
FutureSDR: DEBUG - init blocks
FutureSDR: DEBUG - wait for blocks init
FutureSDR: DEBUG - running blocks
FutureSDR: DEBUG - Listening on 127.0.0.1:1337
FutureSDR: DEBUG - FlowgraphMessage::Terminate
FutureSDR: DEBUG - NullSink_0 terminating 
FutureSDR: DEBUG - NullSource_0 terminating 
FutureSDR: DEBUG - Throttle_0 terminating 
FutureSDR: DEBUG - No active blocks, exiting.
test fg_terminate ... ok
```

**Comment by bastibl** [comment]
I think that, at the moment, we could get the `Terminate` message either from an external source through the flowgraph handle or when a block encounters an error, e.g., during work: https://github.com/FutureSDR/FutureSDR/blob/main/src/runtime/runtime.rs#L561-L567. My understanding is that this solution would only work in the former case, which is why I was suggesting the differentiation between the cases in #80. I thought that a block that fails wouldn't send the `Done` message, required to count down the active blocks. Or maybe I'm missing something.

**Comment by etschneider** [comment]
This sounds like it should be part of the more general discussion of flowgraph lifecycles. I'll add comments on #80 for now.

**Comment by etschneider** [comment]
Ok... I think I'm finally getting your point. So in `runtime::run_block()` change error conditions from:

```rust
main_inbox.send(FlowgraphMessage::Terminate).await?;
```
to:
```rust
main_inbox.send(FlowgraphMessage::Kill).await?;
```

Then in `run_flowgraph()` handle the `Kill` msg differently than `Terminate`?

If I'm on the right track here I can certainly make those changes.

Perhaps instead of kill, something like `FlowgraphMessage::BlockError` might be more descriptive?

But what is the different behavior aside from the return value? 

I think all blocks should still  be given the opportunity to exit gracefully if they can. Even the block that sent the `Kill`. 

I do think there should be a timer set to force exit if some blocks do not reply with `BlockDone`. Perhaps a general periodic `FlowgraphMessage::Tick` would be useful for that (and more). That would ensure that the msg handler gets activated periodically.

Might be useful as a `BlockMessage` too. `Kernel::start()/stop()/tick()` (#86, /me ducks for cover :-> ).

**Comment by bastibl** [comment]
Yes, this is exactly what I meant. `BlockError` and `Terminate` seem like good terms to me.

Regarding the termination logic in case of a block error, we could consider this block as already done and just wait until the number of `BlockDone` plus `BlockError` corresponds to the number of blocks. Or, as it is currently implemented, decrement `active_blocks` in either case.

I'm not a big fan of the `tick`. It's also what GNU Radio is doing. What happened is that several blocks have broken designs and rely on the tick to proceed. Sounds like non-trivial logic to hide block errors.

**Pull request closed without merging**
