### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ratzrattillo**
Update dependencies

Adjust tower error handling to v0.4.0 standards.

### CODE REVIEW

**Comment by ratzrattillo** [comment]
Just saw that some unit tests failed. I will check and try to fix. When commiting i just ran "cargo test" on Windows.

**Comment by ratzrattillo** [comment]
@bastibl would you mind fixing the Vulkan issues? I do not have devices to test.

Another option would be to not update the vulkano crate.

**Comment by bastibl** [comment]
Thanks for the PR. I was looking into the Vulkan changes but they seem a bit more involved. Ideally, the code should also be a bit more typed, i.e., typed Vulkan CPU buffers. But that's a non trivial change. Unfortunately, I won't have the time to look into it in the next few days. So you could just leave out the Vulkan changes for now.

**Comment by bastibl** [comment]
I just pushed a fixed for the clippy warning. (Let's see, if more pop up during the next CI run.)
Are you otherwise done with  the PR?

**Pull request merged**
